### ISSUE TITLE
REST API query interface feature request

### ISSUE THREAD

**Issue by soichih** [esnet/simple-lookup-service#10]
I'd like to be able to select records from multiple service-types. Currently, sLS only allows a single value to be selected, so I will need to make multiple calls to load each record sets.

For example, I'd like to be able to download records with service types with either owamp, bwctl, or traceroute.

```
http://ps-east.es.net:8090/lookup/records/?type=service&group-communities=OSG&service-type=owamp|bwctl|traceroute
```

Please note that,  as of this moment http://ps-east.es.net:8090/ is timing out.

**Comment by soichih** [comment]
Another use case that I popped that I really wished I could do with sLS.

Some services are registered under community "CMS" and some are under "USCMS". I wish I could do something like following

> &group-communities=CMS|USCMS
(| meaning OR)

Or, you could support wildcard search like..

> &group-communities=*CMS

At the moment, I have no choice but to ask CMS administrators to register both CMS and USCMS..

**Comment by sowmyab** [comment]
added wildcard support
