### ISSUE TITLE
Use Testing Framework to mock sLS 

### ISSUE THREAD

**Issue by sowmyab** [esnet/simple-lookup-service#18]
Currently, the sLS relies on outside sLS instance to test its registration and renewal clients. It might be better to mock this behaviour within the testing framework. 

This tasks requires an investigation phase and an implementation phase

**Comment by apertome** [comment]
We're doing some stuff with mocks, let me know if you want to see what we're doing.

**Comment by sowmyab** [comment]
Sure. I would love to see what you are doing with mock.

**Comment by apertome** [comment]
We can discuss it in more detail on a dev call, but here's a simple example. We're using Test::MockObject::Extends

In this test, I'm mocking the part that uses the config daemon to save the changes to the config file:
https://github.com/perfsonar/toolkit/blob/unit-tests/t/host-update_metadata.t

**Comment by sowmyab** [comment]
Integrated mock framework.
