### ISSUE TITLE
sLS throws null pointer exception when registering, editing records when queueservice is turned off

### ISSUE THREAD

**Issue by sowmyab** [esnet/simple-lookup-service#9]
A user reported: 

Basically, I picked a random URI for a record currently stored in my sLS server and ran following.

> curl -v -H "Content-Type: application/json" -X DELETE http://localhost:8090/lookup/service/ea4af87a-5734-4e3f-8dd7-0bce7552efc5

Then I saw following output on sLS.

Sep 23, 2015 12:35:18 PM com.sun.jersey.spi.container.ContainerResponse mapMappableContainerException
SEVERE: The RuntimeException could not be mapped to a response, re-throwing to the HTTP container
java.lang.NullPointerException
        at net.es.lookup.api.EditService.deleteService(EditService.java:224)

However, I was wrong about sLS crashing. Despite the above error message, the sLS server is still up and the record I've requested to DELETE is successfully removed. Also, it looks like above error message is thrown regardless of the type of the record.

And again, with queueservice turned "on", I don't receive any null pointer exception so I am sure this has to do with the queueservice.

**Comment by soichih** [comment]
@sowmyab I was wondering if there is any update on this issue.

I am trying to deploy a pre-production instance of MCA (MeshConfig Admin) and I am currently hit by this problem. I am currently using lookup-service version 2.0-2.

**Comment by sowmyab** [comment]
@soichih 
Can you try this rpm to see if this solves your issue? 

(http://perfsonar-dev.es.net/lookup/lookup-service-2.0-6.noarch.rpm). 

This is still a dev rpm and not a production release so please try it in a test instance.

**Comment by soichih** [comment]
I've installed 2.0-6 on my dev / test instances. I will let it run for a while and see if it can run without crashing. Thanks!

**Comment by sowmyab** [comment]
fixed
